spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mental_journal
    username: root
    password: nisal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true